# Generated by Django 5.1.3 on 2024-11-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0004_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
